### ISSUE TITLE
Trezor signedTypeData released

### ISSUE THREAD

**Issue by 0xShisui** [MetaMask/eth-trezor-keyring#118]
According to the implementation here https://github.com/MetaMask/eth-trezor-keyring/blob/main/index.js#L389 eth_signTypedData are not supported by Trezor.

However, Trezor supports it now:
Implementation : trezor/connect@08e4382
Doc: https://github.com/trezor/connect/blob/develop/docs/methods/ethereumSignTypedData.md

Do you have any plan to add this to Metamask ?

Thank you.

**Comment by aloisklink** [comment]
I've got a PR for adding Trezor T support in https://github.com/MetaMask/eth-trezor-keyring/pull/117, just waiting for somebody from Metamask to review and merge it :smile:

Trezor One support is a bit more complicated: I believe @alisinabh is planning to add it, but is currently waiting for #117 to be merged. But as the Trezor One firmware will only support it in the next release, it's not as urgent.
