### ISSUE TITLE
Standardize repository

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/eth-trezor-keyring#157]
We should update this repository to follow the conventions used in our [module template](https://github.com/MetaMask/metamask-module-template).

**Comment by mikesposito** [comment]
@Gudahtt I think we can now close this and update https://github.com/MetaMask/core/issues/431

**Comment by mikesposito** [comment]
Opa, sorry. Seems like we still miss this: https://github.com/MetaMask/eth-trezor-keyring/issues/165
